### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by AakashSharma7269** [LeonardSSH/coc-discord-rpc#51]
coc-discord-rpc keeps on throwing the following error:
```
[coc.nvim]: UnhandledRejection: TypeError: Cannot read property 'toString' of undefined.
```
Was working till a few days back, have no idea what broke it. Tried reinstalling multiple times only to arrive at the same conclusion.

uname -a:
```
Linux ArchBox 5.13.9-arch1-1 #1 SMP PREEMPT Sun, 08 Aug 2021 11:25:35 +0000 x86_64 GNU/Linux
```

**Comment by ArmoredVortex** [comment]
Facing the same issue

**Comment by iraizo** [comment]
same issue, on arch

**Comment by whisperity** [comment]
Ditto, but affects more than one system. I'm on Ubuntu 18.04 with latest neovim just self-compiled and Coc and this plugin (only!) just reinstalled.

I guess Discord broke the API or something...

**Comment by LeonardSSH** [comment]
Very wierd, I've an extension made with the same RPC Client and it works very great. 

I'll get a virtualbox and see what the extension has.

**Comment by atemmel** [comment]
Posting my full error output here:
```
2021-08-18T20:45:06.862 ERROR (pid:5430) [server] - unhandledRejection  Promise {
  <rejected> TypeError: Cannot read property 'toString' of undefined
      at Function.generateDetails (/home/temmel/Documents/dotfiles/.config/coc/extensions/node_modules/coc-discord-rpc/dist/index.js:2:128864)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Function.generateActivity (/home/temmel/Documents/dotfiles/.config/coc/extensions/node_modules/coc-discord-rpc/dist/index.js:2:127638)
      at async Function.sendActivity (/home/temmel/Documents/dotfiles/.config/coc/extensions/node_modules/coc-discord-rpc/dist/index.js:2:126764)
      at async Function.handleLogin (/home/temmel/Documents/dotfiles/.config/coc/extensions/node_modules/coc-discord-rpc/dist/index.js:2:130754)
} TypeError: Cannot read property 'toString' of undefined
    at Function.generateDetails (/home/temmel/Documents/dotfiles/.config/coc/extensions/node_modules/coc-discord-rpc/dist/index.js:2:128864)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.generateActivity (/home/temmel/Documents/dotfiles/.config/coc/extensions/node_modules/coc-discord-rpc/dist/index.js:2:127638)
    at async Function.sendActivity (/home/temmel/Documents/dotfiles/.config/coc/extensions/node_modules/coc-discord-rpc/dist/index.js:2:126764)
    at async Function.handleLogin (/home/temmel/Documents/dotfiles/.config/coc/extensions/node_modules/coc-discord-rpc/dist/index.js:2:130754)
```

[This](https://github.com/aurieh/discord.nvim) plugin works just fine, however.

**Comment by AakashSharma7269** [comment]
Looks like the project has been abandoned, quite a few issues with no replies.

**Comment by LeonardSSH** [comment]
@

**Comment by LeonardSSH** [comment]
@AakashSharma7269 It's not abandoned, but it's difficult to maintain a project like this that requires a lot of work due to the multitude of distributions this extension can run on. And to be honest, I don't have the desire or motivation to start racking my brain.

**Comment by AakashSharma7269** [comment]
@LeonardSSH Understandable.

**Comment by LeonardSSH** [comment]
@AakashSharma7269 If you can to fix it, you can do a PR, it would be welcome. 😅

**Comment by AakashSharma7269** [comment]
I believe this is out of my skill set, but i'll try.

**Comment by excalios** [comment]
I would like to try to fix it is there any guide on how to test it? I set the runtime path but it doesn't show anything

**Comment by LeonardSSH** [comment]
A new version has been released, along with @excalios fix, I hope this fix resolves the reported issue. Please let me know if it's resolved.

**Comment by LeonardSSH** [comment]
UPDATE: Apparently, @excalios's fix solves the problem, but not entirely, now I've discovered why the problem occurs, and am almost ready to fix it.

**Comment by LeonardSSH** [comment]
https://github.com/LeonardSSH/coc-discord-rpc/commit/d123a583ab9f829d60aeeea4b531a10127f67d52 solves the problem entirely. In the next few minutes, a new version patch for this issue will be released.

**Comment by LeonardSSH** [comment]
Please update the extension and let me know if it's fixed. @excalios @AakashSharma7269 @atemmel @whisperity @iraizo @ArmoredVortex

**Comment by AakashSharma7269** [comment]
The plugin works perfectly now. Thank you @LeonardSSH and @excalios <3
